### ISSUE TITLE
重大BUG, 七牛官方修改了.URL

### ISSUE THREAD

**Issue by cxc222** [iwillwen/qiniu.js#11]
以前是 空间名.qiniudn.com 现在都是 
7sbr7s.com2.z0.glb.qiniucdn.com
7sbr7s.com2.z0.glb.clouddn.com

这种形式, 能修改吗? 域名这块自定义

**Comment by bohanyang** [comment]
你可以在上传完毕时获取文件名，和域名拼接即可。我的 Demo http://windlab.sinaapp.com/QiniuUploader/
