### ISSUE TITLE
JS 得到 html5 画图的 base64 的值，不通过后端可以实现吗？

### ISSUE THREAD

**Issue by weianzi** [iwillwen/qiniu.js#13]
JS 得到 html5 画图的 base64 的值，我要上传到七牛，返回图片的地址！
关于上传base64 有没有文档？
谢谢

**Comment by iwillwen** [comment]
你是指 Canvas 里获得的 base64 值吧？Canvas 对象可以直接用 `toBlob` 方法获得一个 Blob 对象，你可以直接把这个 Blob 对象作为 File 对象上传到七牛。
详细参见：https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
