### ISSUE TITLE
在我的meteor项目中， npm安装后， 导致项目无法运行。

### ISSUE THREAD

**Issue by leefurong** [iwillwen/qiniu.js#15]
![image](https://cloud.githubusercontent.com/assets/1957050/16707291/1a6c73fa-45fb-11e6-974b-cb6800b984d8.png)

**Comment by iwillwen** [comment]
@leefurong 你好，這個 SDK 是只能夠運行在瀏覽器環境中的，不能使用 Node.js 環境運行。如果你需要在 Node.js 環境中進行七牛云存儲數據操作，那麼可以使用這個 Node.js SDK [node-qiniu](https://github.com/iwillwen/node-qiniu)。
